version: "3.6"

services:
  api-mongo-service:
    container_name: 'api-mongo-service'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_USERNAME=mongodb
      - MONGO_INITDB_PASSWORD=password
    ports:
      - 27017:27017